### ISSUE TITLE
How to go about the installation

### ISSUE THREAD

**Issue by mickeymond** [Beincrypto/strapi-plugin-web3-login#10]
@jffernandez I want to try to use this package and contribute to improving it along the way.
Right now I am finding it hard to install because it cannot be found on npm.

**Comment by mickeymond** [comment]
@jffernandez Are you up for taking this package and hosting it on NPM to make installation easy?

**Comment by jffernandez** [comment]
Hello @mickeymond You can easily install a package from GitHub directly using your package manager (yarn, npm, ...), for example, with npm:
`npm install beincrypto/strapi-plugin-web3-login`

https://www.geeksforgeeks.org/how-to-install-an-npm-package-directly-from-github/
